name: Build & Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Add Gradlew privileges
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build