name: Build

on:
  push:
    branches:
      - ci

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Gradlew privileges
        run: chmod +x ./gradlew
          
      - name: Build
        run: ./gradlew build
